name: "web_app"
# gin框架运行模式,可选值: debug, release, test
ginMode: "debug"
# 调试模式(控制台输出详细日志),可选值: dev, prod
mode: "dev"
version: "0.0.1"
# start time 尽量写近期时间,但不要写未来时间,可以延迟使用
startTime: "2022-07-25"
# 尽量不同机器,ID不同
machineId: 1
# 容器部署不要填127.0.0.1
host: "0.0.0.0"
port: 12345

auth:
  jwt_expire: 8760h

mysql:
  host: "192.168.118.138"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  maxOpenConns: 100
  maxIdleConns: 50

redis:
  host: "192.168.118.138"
  port: 6379
  password: "123456"
  db: 0
  poolSize: 100

log:
  level: "debug"
  filename: "./app.log"
  # 单个日志最大10MB
  maxSize: 10
  maxBackups: 5
  # 保存7天
  maxAge: 7